In [1]:
import pandas as pd
import numpy as np

In [2]:
data= pd.read_csv('deliveries.csv')

In [3]:

data

,match_id,season,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,striker_id,non_striker_id,bowler_id
0,829723,2015,1,0.1,Chennai Super Kings,Kolkata Knight Riders,DR Smith,BB McCullum,PJ Cummins,0,...,NaN,NaN,NaN,caught,DR Smith,NaN,NaN,35205dfc,b8a55852,ded9240e
1,829765,2015,1,0.1,Chennai Super Kings,Kolkata Knight Riders,DR Smith,BB McCullum,PJ Cummins,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35205dfc,b8a55852,ded9240e
2,829765,2015,1,0.2,Chennai Super Kings,Kolkata Knight Riders,DR Smith,BB McCullum,PJ Cummins,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35205dfc,b8a55852,ded9240e
3,829765,2015,1,0.3,Chennai Super Kings,Kolkata Knight Riders,DR Smith,BB McCullum,PJ Cummins,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35205dfc,b8a55852,ded9240e
4,829765,2015,1,0.4,Chennai Super Kings,Kolkata Knight Riders,DR Smith,BB McCullum,PJ Cummins,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35205dfc,b8a55852,ded9240e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,501243,2011,2,7.2,Delhi Daredevils,Deccan Chargers,V Sehwag,TR Birt,I Malhotra,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ba8195d,d2d4bb0a,943fd425
225950,501243,2011,2,7.3,Delhi Daredevils,Deccan Chargers,V Sehwag,TR Birt,I Malhotra,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ba8195d,d2d4bb0a,943fd425
225951,501243,2011,2,7.4,Delhi Daredevils,Deccan Chargers,V Sehwag,TR Birt,I Malhotra,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ba8195d,d2d4bb0a,943fd425
225952,501243,2011,2,7.5,Delhi Daredevils,Deccan Chargers,V Sehwag,TR Birt,I Malhotra,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ba8195d,d2d4bb0a,943fd425
225953,501243,2011,2,7.6,Delhi Daredevils,Deccan Chargers,V Sehwag,TR Birt,I Malhotra,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ba8195d,d2d4bb0a,943fd425

In [4]:
def over_generator(data):
    for i in range(20):
        for x in range(data.shape[0]):
            if i < data['ball'][x] < i + 1:
                data['over'][x] = i + 1
    return data

In [ ]:
data['over']=0
data = over_generator(data)
data

C:\Users\Aryan Chaturvedi\AppData\Local\Temp\ipykernel_16768\3365398494.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['over'][x] = i + 1